# Generated by Django 4.1.2 on 2022-11-04 11:27

import core.managers
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usersession_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shippingaddress',
            managers=[
                ('objects', core.managers.CustomModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='usersession',
            managers=[
                ('objects', core.managers.CustomModelManager()),
            ],
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='데이터가 생성된 일자입니다.', verbose_name='생성일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='데이터를 삭제한 일자입니다.', null=True, verbose_name='삭제일'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, editable=False, help_text='데이터 삭제 여부입니다.', verbose_name='삭제 여부'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='데이터가 수정된 사용자입니다.', verbose_name='수정일'),
        ),
    ]
