# Generated by Django 4.1.2 on 2022-11-30 07:15

import core.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_shippingaddress_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.managers.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='auth_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='인증번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='- 를 제외한 번호만 입력하세요.', max_length=11, verbose_name='휴대폰'),
        ),
    ]
