# Generated by Django 4.1.2 on 2022-10-17 08:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shop.models.category
import shop.models.review


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='데이터가 생성된 일자입니다.', verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='데이터가 수정된 사용자입니다.', verbose_name='수정일')),
                ('is_deleted', models.BooleanField(blank=True, default=False, editable=False, help_text='데이터 삭제 여부입니다.', verbose_name='삭제 여부')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='데이터를 삭제한 일자입니다.', null=True, verbose_name='삭제일')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='카테고리 이름')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='슬러그 필드')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=shop.models.category.category_thumbnail_upload_to, verbose_name='썸네일')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
                'db_table': 'category_tb',
            },
        ),
        migrations.CreateModel(
            name='CategoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='데이터가 생성된 일자입니다.', verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='데이터가 수정된 사용자입니다.', verbose_name='수정일')),
                ('is_deleted', models.BooleanField(blank=True, default=False, editable=False, help_text='데이터 삭제 여부입니다.', verbose_name='삭제 여부')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='데이터를 삭제한 일자입니다.', null=True, verbose_name='삭제일')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='세부 카테고리 이름')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='슬러그 필드')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=shop.models.category.category_detail_thumbnail_upload_to, verbose_name='썸네일')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_category', to='shop.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '세부 카테고리',
                'verbose_name_plural': '세부 카테고리',
                'db_table': 'category_detail_tb',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='데이터가 생성된 일자입니다.', verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='데이터가 수정된 사용자입니다.', verbose_name='수정일')),
                ('is_deleted', models.BooleanField(blank=True, default=False, editable=False, help_text='데이터 삭제 여부입니다.', verbose_name='삭제 여부')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='데이터를 삭제한 일자입니다.', null=True, verbose_name='삭제일')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='상품명')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='슬러그 필드')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('supply_price', models.PositiveIntegerField(default=0, verbose_name='공급가액')),
                ('amount', models.PositiveIntegerField(verbose_name='금액')),
                ('tax', models.PositiveIntegerField(default=0, verbose_name='세금')),
                ('sale_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='할인율')),
                ('sale_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='할인가')),
                ('stock', models.PositiveIntegerField(verbose_name='수량')),
                ('is_halal', models.BooleanField(db_index=True, default=False, verbose_name='할랄')),
                ('is_public', models.BooleanField(db_index=True, default=False, verbose_name='판매 가능 여부')),
                ('best_item', models.BooleanField(db_index=True, default=True, verbose_name='베스트 아이템')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_category', to='shop.categorydetail', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
                'db_table': 'item_tb',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='데이터가 생성된 일자입니다.', verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='데이터가 수정된 사용자입니다.', verbose_name='수정일')),
                ('is_deleted', models.BooleanField(blank=True, default=False, editable=False, help_text='데이터 삭제 여부입니다.', verbose_name='삭제 여부')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='데이터를 삭제한 일자입니다.', null=True, verbose_name='삭제일')),
                ('review', models.TextField()),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='별점')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_item', to='shop.item', verbose_name='상품')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='shop.review', verbose_name='대댓글을 작성할 댓글')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '리뷰',
                'verbose_name_plural': '리뷰',
                'db_table': 'review_tb',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='데이터가 생성된 일자입니다.', verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='데이터가 수정된 사용자입니다.', verbose_name='수정일')),
                ('is_deleted', models.BooleanField(blank=True, default=False, editable=False, help_text='데이터 삭제 여부입니다.', verbose_name='삭제 여부')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='데이터를 삭제한 일자입니다.', null=True, verbose_name='삭제일')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.models.review.review_image_upload_to, verbose_name='이미지')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_review', to='shop.review', verbose_name='리뷰')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='데이터가 생성된 일자입니다.', verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='데이터가 수정된 사용자입니다.', verbose_name='수정일')),
                ('is_deleted', models.BooleanField(blank=True, default=False, editable=False, help_text='데이터 삭제 여부입니다.', verbose_name='삭제 여부')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='데이터를 삭제한 일자입니다.', null=True, verbose_name='삭제일')),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_image_upload_to', verbose_name='상품 이미지')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_item', to='shop.item', verbose_name='상품')),
            ],
            options={
                'verbose_name': '상품 이미지',
                'verbose_name_plural': '상품 이미지',
                'db_table': 'item_image_tb',
                'ordering': ['-id'],
            },
        ),
    ]
