# Generated by Django 4.1.2 on 2022-12-01 15:12

import core.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_item_best_item_alter_review_review_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('objects', core.managers.CustomModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='categorydetail',
            managers=[
                ('objects', core.managers.CustomModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='item',
            managers=[
                ('objects', core.managers.CustomModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='itemimage',
            managers=[
                ('objects', core.managers.CustomModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='review',
            managers=[
                ('objects', core.managers.CustomModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='reviewimage',
            managers=[
                ('objects', core.managers.CustomModelManager()),
            ],
        ),
    ]
