# Generated by Django 4.1.2 on 2022-12-24 12:44

import core.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_category_alter_item_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='데이터가 생성된 일자입니다.', verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='데이터가 수정된 사용자입니다.', verbose_name='수정일')),
                ('is_deleted', models.BooleanField(blank=True, default=False, editable=False, help_text='데이터 삭제 여부입니다.', verbose_name='삭제 여부')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='데이터를 삭제한 일자입니다.', null=True, verbose_name='삭제일')),
                ('name', models.CharField(max_length=100, verbose_name='옵션명')),
                ('value', models.CharField(max_length=100, verbose_name='옵션값')),
            ],
            options={
                'verbose_name': '상품 옵션',
                'verbose_name_plural': '상품 옵션',
                'db_table': 'item_option_tb',
                'ordering': ['id'],
            },
            managers=[
                ('objects', core.managers.CustomModelManager()),
            ],
        ),
        migrations.CreateModel(
            name='ItemReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='데이터가 생성된 일자입니다.', verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='데이터가 수정된 사용자입니다.', verbose_name='수정일')),
                ('is_deleted', models.BooleanField(blank=True, default=False, editable=False, help_text='데이터 삭제 여부입니다.', verbose_name='삭제 여부')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='데이터를 삭제한 일자입니다.', null=True, verbose_name='삭제일')),
                ('name', models.CharField(max_length=100, verbose_name='옵션명')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='수량')),
                ('safe_quantity', models.PositiveSmallIntegerField(verbose_name='안전 수량')),
                ('extra_amount', models.PositiveSmallIntegerField(verbose_name='추가 금액')),
                ('is_public', models.BooleanField(db_index=True, default=False, verbose_name='판매 가능 여부')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_item', to='shop.item', verbose_name='상품')),
            ],
            options={
                'verbose_name': '상품 실물',
                'verbose_name_plural': '상품 실물',
                'db_table': 'item_real_tb',
                'ordering': ['id'],
            },
            managers=[
                ('objects', core.managers.CustomModelManager()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='option',
            field=models.ManyToManyField(blank=True, null=True, related_name='%(class)s_option', to='shop.itemoption', verbose_name='상품 옵션'),
        ),
    ]
