# Generated by Django 4.1.2 on 2022-12-24 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_itemoption_itemreal_item_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='option',
        ),
        migrations.RemoveField(
            model_name='item',
            name='supply_price',
        ),
        migrations.AddField(
            model_name='item',
            name='supply_amount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='공급가액'),
        ),
        migrations.AddField(
            model_name='itemoption',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_item', to='shop.item', verbose_name='상품'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.PositiveSmallIntegerField(verbose_name='금액'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sale_amount',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='할인가'),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.PositiveSmallIntegerField(verbose_name='수량'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tax',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='세금'),
        ),
        migrations.AlterField(
            model_name='itemreal',
            name='extra_amount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='추가 금액'),
        ),
        migrations.AlterField(
            model_name='itemreal',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='수량'),
        ),
        migrations.AlterField(
            model_name='itemreal',
            name='safe_quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='안전 수량'),
        ),
    ]
