# Generated by Django 4.1.2 on 2023-01-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_item_option_remove_item_supply_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='options',
            field=models.TextField(default='', verbose_name='상품 옵션'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ItemOption',
        ),
    ]
