# Generated by Django 4.1.2 on 2022-10-17 08:53

import accounts.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='데이터가 생성된 일자입니다.', verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='데이터가 수정된 사용자입니다.', verbose_name='수정일')),
                ('is_deleted', models.BooleanField(blank=True, default=False, editable=False, help_text='데이터 삭제 여부입니다.', verbose_name='삭제 여부')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='데이터를 삭제한 일자입니다.', null=True, verbose_name='삭제일')),
                ('merchant_uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='주문번호')),
                ('imp_uid', models.CharField(blank=True, max_length=100, verbose_name='아임포트 거래고유번호')),
                ('name', models.CharField(max_length=100, verbose_name='상품명')),
                ('amount', models.PositiveIntegerField(verbose_name='결제금액')),
                ('delivery_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='배송비')),
                ('first_name', models.CharField(max_length=50, verbose_name='성')),
                ('last_name', models.CharField(max_length=50, verbose_name='이름')),
                ('buyer_postcode', models.CharField(max_length=20, verbose_name='우편번호')),
                ('buyer_addr', models.CharField(max_length=100, verbose_name='주소')),
                ('detail_address', models.CharField(max_length=100, verbose_name='상세주소')),
                ('buyer_email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('buyer_tel', models.CharField(max_length=11, validators=[accounts.validators.validate_phone_length], verbose_name='전화번호')),
                ('exchange_return', models.BooleanField(db_index=True, default=False, verbose_name='교환/반품')),
                ('delivery_number', models.CharField(blank=True, max_length=15, verbose_name='등기번호')),
                ('status', models.CharField(choices=[('ready', '미결제'), ('paid', '결제완료'), ('cancelled', '결제취소'), ('failed', '결제실패'), ('exchange_return', '교환/반품'), ('shipping_ready', '배송준비'), ('shipping', '배송중'), ('shipping_complete', '배송완료')], db_index=True, default='ready', max_length=17, verbose_name='처리상태')),
                ('pay_method', models.CharField(choices=[('card', '신용카드'), ('trans', '실시간계좌이체'), ('vbank', '가상계좌'), ('phone', '휴대폰소액결제')], default='card', max_length=5, verbose_name='결제 수단')),
                ('vbank_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='가상계좌')),
                ('meta', models.TextField(blank=True, null=True, verbose_name='메다 데이터')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL, verbose_name='구매자')),
            ],
            options={
                'verbose_name': '주문정보',
                'verbose_name_plural': '주문정보',
                'db_table': 'order_tb',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='데이터가 생성된 일자입니다.', verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='데이터가 수정된 사용자입니다.', verbose_name='수정일')),
                ('is_deleted', models.BooleanField(blank=True, default=False, editable=False, help_text='데이터 삭제 여부입니다.', verbose_name='삭제 여부')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='데이터를 삭제한 일자입니다.', null=True, verbose_name='삭제일')),
                ('status', models.CharField(choices=[('ready', '미결제'), ('paid', '결제완료'), ('cancelled', '결제취소'), ('failed', '결제실패'), ('exchange_return', '교환/반품'), ('shipping_ready', '배송준비'), ('shipping', '배송중'), ('shipping_complete', '배송완료')], db_index=True, default='ready', max_length=17, verbose_name='처리상태')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_order', to='order.order', verbose_name='주문정보')),
            ],
            options={
                'verbose_name': '주문 처리상태 로그',
                'verbose_name_plural': '주문 처리상태 로그',
                'db_table': 'order_status_log_tb',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='데이터가 생성된 일자입니다.', verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='데이터가 수정된 사용자입니다.', verbose_name='수정일')),
                ('is_deleted', models.BooleanField(blank=True, default=False, editable=False, help_text='데이터 삭제 여부입니다.', verbose_name='삭제 여부')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='데이터를 삭제한 일자입니다.', null=True, verbose_name='삭제일')),
                ('quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('delivery_number', models.CharField(blank=True, max_length=15, verbose_name='등기번호')),
                ('status', models.CharField(choices=[('ready', '미결제'), ('paid', '결제완료'), ('cancelled', '결제취소'), ('failed', '결제실패'), ('exchange_return', '교환/반품'), ('shipping_ready', '배송준비'), ('shipping', '배송중'), ('shipping_complete', '배송완료'), ('exchange_ready', '교환접수요청'), ('exchange_receipt', '교환접수'), ('exchanging', '교환처리중'), ('exchange_complete', '교환완료'), ('exchange_fail', '교환실패'), ('exchange_cancel', '교환취소'), ('return_ready', '반품접수요청'), ('return_receipt', '반품접수'), ('returning', '반품처리중'), ('return_complete', '반품완료'), ('return_fail', '반품실패'), ('return_cancel', '반품취소')], db_index=True, default='ready', max_length=17, verbose_name='처리상태')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_item', to='shop.item', verbose_name='상품명')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_order', to='order.order', verbose_name='주문정보')),
            ],
            options={
                'verbose_name': '주문상품',
                'verbose_name_plural': '주문상품',
                'db_table': 'order_item_tb',
                'ordering': ['-id'],
            },
        ),
    ]
