# Generated by Django 4.1.2 on 2022-11-12 14:59

import core.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('objects', core.managers.CustomModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orderitem',
            managers=[
                ('objects', core.managers.CustomModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orderstatuslog',
            managers=[
                ('objects', core.managers.CustomModelManager()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='merchant_uid',
            field=models.UUIDField(verbose_name='주문번호'),
        ),
    ]
