# Generated by Django 4.1.2 on 2023-01-24 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_item_options_delete_itemoption'),
        ('order', '0003_rename_last_name_order_buyer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer_tel',
            field=models.CharField(max_length=11, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='order',
            name='meta',
            field=models.TextField(blank=True, null=True, verbose_name='메타 데이터'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_item', to='shop.itemreal', verbose_name='상품실물'),
        ),
    ]
